services:
  selenium:
    image: selenium/standalone-chrome:120.0
    shm_size: 2gb
    ports:
      - "4444:4444"  # WebDriver port
      - "7900:7900"  # VNC port (to be enabled)
    environment:
      - SE_NODE_MAX_INSTANCES=1
      - SE_NODE_MAX_SESSIONS=1
      - SE_VNC_NO_PASSWORD=1  # Allow VNC without password
      - START_XVFB=true  # Start virtual display

  tests:
    build: .
    depends_on:
      - selenium
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
